version: '3.1'
services:
  postgres:
    image: postgres:9.3

  possum:
    image: possum:latest
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    depends_on:
      - postgres

  test:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - possum
    volumes:
      - .:/build
    environment:
      CONJUR_APPLIANCE_URL: http://possum
      CONJUR_ACCOUNT: cucumber
