version: '2'
services:
  postgres:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.1.0-stable
    command: server -a cucumber
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  conjur-proxy-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    entrypoint: nginx-debug -g 'daemon off;'
    environment:
        TERM: xterm
    ports:
    - "8080:80"
    - "8443:443"
    depends_on:
      - conjur
      - client


  client:
    image: conjurinc/cli5
    volumes:
      - ./test-cert:/test-cert
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    depends_on:
      - conjur

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./target:/conjurinc/api-java/target
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber


  test-https:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./target:/conjurinc/api-java/target
      - ./test-cert:/test-cert
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-proxy-nginx
      CONJUR_ACCOUNT: cucumber
    depends_on:
      - conjur-proxy-nginx